### ISSUE TITLE
Fechamento de PLPs

### ISSUE THREAD

**Issue by ysads** [Sidoniuns/sigep_web#4]
Olá!

Antes de mais nada, parabéns pela gem desenvolvida. Ela é realmente muito fácil de usar. Porém, algo não ficou muito claro para mim... Ela gera fecha as PLPs e retorna um objeto contendo os dados da PLP gerada (ids, dimensões e informações dos objetos a serem postados, código de rastreamento)?

Pergunto pois preciso gerar um etiqueta de postagem a partir de uma PLP, e estou um pouco perdido sobre como fazer isso em Ruby.

Obrigado!

**Comment by marceloperini** [comment]
Muito obrigado @ysads 

primeiramente dê uma olhada na documentação da API do Sigep Web [http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf](url)

praticamente todos os métodos dessa gema correspondem a um endpoint dessa Api.

O fluxo para gerar uma plp é:
1. solicitar os códigos de rastreamento;
2. gerar o dígito verificador para cada código;
3. criar a estrutura do destinatário;
4. definir as dimensões dos objetos de postagem;
5. definir os objetos de postagem;
6. definir o remetente
7. requisitar a plp;

**1. Solicitar os códigos de rastreamento**

corresponde ao endpoint solicitaEtiquetas da Api

Para solicitar os códigos de rastreamento você precisará utilizar o método _request_labels_ da gema:

``` ruby
SigepWeb.request_labels(receiver_type: 'C', identifier: '000000000000',
                        id_service: '104625', qt_labels: 1)
```

- receiver_type: tipo do destinatário, para clientes use C
- identifier: identificador da empresa contratante, aqui você vai colocar o CNPJ dela, use somente os números
- id_service: id do serviço que deseja utilizar (SEDEX, PAC, etc.) esse id pode ser obtido através do método _SigepWeb.search_client_, neste exemplo o número 104625 corresponde ao SEDEX
- qt_labels: quantidade de códigos você quer solicitar, eu recomendo solicitar um por vez para cada produto que você quer enviar, pois a API tem limites de código por solicitação

o método retorna uma _hash_, contendo os atributos _success_ e _response_, se der tudo certo, _success_ será _true_, caso contrário _false_. _Response_ vai retornar uma _array_ de códigos (sem o dígito verificador):

``` ruby
  { success: true, response: ['DL61145929 BR'] }
```

**2. Gerar o dígito verificador para cada código**

corresponde ao endpoint geraDigitoVerificadorEtiquetas da Api

para gerar o dígito verificador para o código de rastreamento você precisará utilizar o método _generate_labels_digit_verifier_ da gema:

``` ruby
  SigepWeb.generate_labels_digit_verifier(labels: 'DL61145929 BR')
```

- labels: _array_ contendo os códigos de rastreamento ou somente uma _string_ com o código, caso deseje gerar o digito somente um

o método retorna uma _hash_ contendo _success_ e _response_, a ideia desses dois atributos é o mesmo para todos métodos. Caso o método seja invocado com um _array_ de códigos de rastreamento, o retorno trará um array de dígitos verificadores:

```ruby
  { success: true, response: 6 }
```

* Obs.: o dígito verificador fica no espaço em branco do código de rastreamento, para este exemplo, temos o código 'DL61145929 BR' e o dígito 6, logo o código de rastreamento final ficará 'DL611459296BR'.

**3. Criar a estrutura do destinatário**

para definir um destinatário você irá utilizar o método _SigepWeb::Models::Receiver.new_:

```ruby
SigepWeb::Models::Receiver.new(name: 'Josefina',
                               email: 'josefina@foo.com',
                               number: '10',
                               address: 'Rua X',
                               complement: 'Perto da rua X+1',
                               neighborhood: 'Bairro X-1',
                               city: 'Cidade Y',
                               uf: 'SP', amount: '0,0',
                               cep: '04105-070')
```

- name: nome do destinatário
- email: e-mail do destinatário
- number: número do endereço destinatário
- address: logradouro destinatário
- complement: complemento do endereço
- neighborhood: bairro destinatário
- city: cidade
- uf: estado
- cep: CEP
- amount: valor para casos de postagem a cobrar

**4. Definir as dimensões dos objetos de postagem**

utilize o método _SigepWeb::Models::DimensionObject.new_:

```ruby
SigepWeb::Models::DimensionObject.new(object_type: '002', height: '20',
                                      width: '30', length: '38',
                                      diameter: '0')
```

- object_type: tipo do objeto (001 - Envelope, 002 - Pacote / Caixa, 003 - Rolo / Cilindro)
- height: altura em cm
- width: largura em cm
- length: comprimento em cm
- diameter: diâmetro em cm

**5. Definir os objetos de postagem**

utilize o método _SigepWeb::Models::PostalObject.new_:

```ruby
SigepWeb::Models::PostalObject.new(label_number: 'DL611459296BR',
                                   postage_code_service: '40096',
                                   cubage: 0.0,
                                   weight: '400',
                                   receiver: receiver,
                                   dimension_object: dimension_object,
                                   processing_status: '0')
```

- label_number: código de rastreamento já com o dígito verificador
- postage_code_service: código de serviço a ser utilizado (SEDEX, PAC, etc.), para esse caso foi utilizado o SEDEX, para ver todos os códigos de serviço disponíveis para o cliente utilize o método _SigepWeb.search_client_
- cubage: cubagem do objeto (em centimetros cúbicos), preencher com o valor 0.0
- weight: peso do objeto em gramas (valor apróximado, na agéncia dos correios o objeto será pesado novamente)
- receiver: o objeto instanciado da classe _SigepWeb::Models::Receiver_ (item 3)
- dimension_object: o objeto instanciado da classe _SigepWeb::Models::DimensionObject_ (item 4)
- processing_status: status de processamento, sempre preencher com valor '0'

**6. Definir o remetente**

utilize o método _SigepWeb::Models::Sender.new_:

```ruby
SigepWeb::Models::Sender.new(directorship_number: '16',
                             name: 'Loja X',
                             address: 'Rua X', number: '10',
                             complement: 'perto da rua X+1',
                             neighborhood: 'Bairro Y',
                             zip_code: '7400000', city: 'Goiânia',
                             uf: 'GO', email: 'contato@loja_x.com.br',
                             postal_objects: postal_objects)
```

- directorship_number: número da diretoria regional do contrato do cliente
- name: nome do remetente
- address: logradouro
- number: número do endereço
- complement: complemento
- neighborhood: bairro
- zip_code: código postal (CEP)
- city: cidade
- uf: estado
- email: e-mail do remetente
- postal_objects: array contendo instancias da classe _SigepWeb::Models::PostalObject_ (item 5)

**7. Requisitar a plp**

utilize o método _SigepWeb.request_plp_services_:

```ruby
SigepWeb.request_plp_services(plp: sender, id_plp_client: 00_000_000,
                              labels: labels)
```

- plp: instancia da classe _SigepWeb::Models::Sender_ (item 6)
- id_plp_client: código gerado pelo cliente para identificação da PLP
- labels: array contendo todos os códigos de rastreamento solicitado (sem o dígito verificador, remova o espaço do digito), exemplo: ['DL61145929BR']


Muito obrigado por utilizar a minha gema, fico muito feliz em poder ajudar, caso necessite de qualquer informação não exite em perguntar. Me desculpe por ainda não ter feito uma documentação decente.

**Comment by marceloperini** [comment]
@ysads estarei fechando a issue, caso tenha alguma outra dúvida pode criar outra, ou enviar um email para [marcelo.perini.veloso@gmail.com](mailto:marcelo.perini.veloso@gmail.com)
