### ISSUE TITLE
Uso da variável de ambiente GEM_ENV

### ISSUE THREAD

**Issue by mathportillo** [Sidoniuns/sigep_web#5]
Olá,

Muito obrigado pela gem! É a melhor disponível pra uso do SIGEP.

Ao escrever testes pra minha aplicação usando credenciais de teste da documentação do Correios, recebia sempre o seguinte erro:

> `(soap:Server) A autenticacao de sigep falhou!`

Ao investigar percebi que `WebServiceInterfaceApi` utiliza a variável de ambiente `GEM_ENV` pra definir a host da chamadas.

Acontece que atualmente a base de suite de teste usada pelo _rspec_ usa por padrão a variável `RAILS_ENV` e não `GEM_ENV`. E porque no meu caso o `GEM_ENV` não estava definido, meus testes estavam batendo no host de produção do correios, e não no de teste, e por isso havia falha de autenticação.

Ao definir `GEN_ENV` com o valor `test`, o erro foi corrigido.

Sugiro humildemente que seja feito uma dessas duas possibilidades:

1. Que o uso da variável `GEM_ENV` seja documentado
2. Que o `WebServiceInterfaceApi` use a variável de ambiente `RAILS_ENV` ao invés de `GEM_ENV`.

Obrigado!

**Comment by marceloperini** [comment]
Muito obrigado pelo seu feedback @mathportillo. Legal a sua observação, acho que o ideal seria incluir uma verificação no uso de um framework específico que é o caso do Rails, ou até mesmo uma verificação das duas ENVs, já que a ideia dessa Gem é utilizar em qualquer projeto com Ruby e não só com Rails. Hoje mesmo estarei disponibilizando uma nova versão corrigindo esse problema.

Obrigado.

**Comment by mathportillo** [comment]
É verdade!
Eu esqueci que a gem pode ser usada fora do Rails.
Muito obrigado novamente.

**Comment by marceloperini** [comment]
@mathportillo essa tarde lancei a versão 0.2.7 da gem, confere pra mim se o problema foi resolvido, vou manter a issue aberta até você me der um feedback positivo

**Comment by mathportillo** [comment]
Resolvido!
Funciona com a configuração padrão do Rspec em projetos Rails.

Muito Obrigado!

**Comment by marceloperini** [comment]
Obrigado. Qualquer coisa pode abrir outra issue.
